[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/tsuru/tsuru"
  branch = "master"

[[override]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.4"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"

[[constraint]]
  name = "istio.io/istio"
  version = "1.0.2"
